import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import GlobalHeader from "@/ui/globalheader";
import GlobalSidebar from "@/ui/globalsidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="min-h-screen bg-[#F1F5F9] text-[#1E293B] font-sans">
              
          {/* 1. TOP NAVIGATION / HEADER */}
          <GlobalHeader />
    
          <div className="max-w-[1400px] mx-auto grid grid-cols-1 md:grid-cols-12 gap-6 p-4 md:p-6">
            
            {/* --- LEFT SIDEBAR: LEAGUES --- */}
            <GlobalSidebar />
    
            {/* --- MAIN CONTENT --- */}
            {children}
    
          </div>
        </div>
      </body>
    </html>
  );
}
